### ISSUE TITLE
Warning: Declaration in Proxy Class (Flow_Object_Classes)

### ISSUE THREAD

**Issue by zdreicom** [neos/flow-development-collection#1191] opened 2018-01-23 13:58 UTC
## Description

Using declare(strict_types=1); I get an error Warning: Declaration … should be compatible with … in my case the proxy class Z3_Crm_Controller_CallAgentController.php for CallAgentController extends from CallAgentController_Original

in CallAgentController_Original the declaration of Contact is right

public function nextAction(Contact $contact, string $type = ‘’, string $text = ‘’)

in CallAgentController not any more

public function nextAction($contact, string $type = ‘’, string $text = ‘’)

This trigged the error (warning)

## Expected behavior

The proxy-builder also adds the typen declaration to the proxy class CallAgentController

## Affected Versions

* Neos Flow 4.3.2 and before
* PHP 7.1

**Comment by bwaidelich** [comment] 2018-02-01 16:46
Thanks for reporting!
This is probably related to #1151 – I'll have a look

**Comment by bwaidelich** [comment] 2018-02-01 17:06
In my first experiment with Flow 3.3 I can't reproduce the issue.

*StandardController.php*:
```php
<?php
declare(strict_types=1);
namespace Wwwision\Test\Controller;

use TYPO3\Flow\Mvc\Controller\ActionController;
use Wwwision\Test\Contact;

class StandardController extends ActionController
{
    public function nextAction(Contact $contact, string $type = '', string $text = '')
    {
        return 'Contact: ' . $contact->getName();
    }
}
```

Generated proxy class:

```php
class StandardController extends StandardController_Original implements \TYPO3\Flow\Object\Proxy\ProxyInterface {

    // ...

    /**
     * Autogenerated Proxy Method
     */
    public function nextAction(\Wwwision\Test\Contact $contact, string $type = '', string $text = '')
    {

   // ...
```


I'll check if I can reproduce it with Flow 4.3

**Comment by bwaidelich** [comment] 2018-02-01 17:14
The same with Flow 4.3: I can't reproduce the problem and the [code](https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/ObjectManagement/Proxy/ProxyMethod.php#L270) suggests that the type hint is added to the proxy class as expected.

@zdreicom could you maybe provide a minimal example?

**Comment by bwaidelich** [comment] 2018-02-23 15:57
Closing due to lack of reproducibility & feedback. @zdreicom Feel free to re-open if the issue still exists for you

**Closed by bwaidelich** 2018-02-23 15:57 UTC
Labels: Bug, P: Flow, T: PHP
