### ISSUE TITLE
Custom error views configuration is broken

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#1108] opened 2017-11-08 08:02 UTC
### Description

When following https://flowframework.readthedocs.io/en/latest/TheDefinitiveGuide/PartIII/ErrorAndExceptionHandling.html#custom-error-views in a Flow version starting with 4.0 the results will not be as expected.

### Steps to Reproduce

1. Configure a custom error view as documented
2. Trigger an exception
3. Marvel at the expected template not being shown

#### Expected behavior

The custom template should be used.

#### Actual behavior

No template is used.

### Affected Versions

Flow: 4.0 (since the introduction of TYPO3Fluid, presumably)

**Comment by kdambekalns** [comment] 2017-11-08 08:09
The reason for this behaviour is as follows:

When rendering an exception using `echoExceptionWeb()` both the production and the debug exception handler check for `$this->renderingOptions['templatePathAndFilename'])` first, to see if a custom view is defined.

If that is the case, `buildView()` is used. That builds a view based on `$renderingOptions['viewOptions']` (with `viewOptions` not even mentioned in the documentation.) Then a method called `applyLegacyViewOptions()` is called, which uses `ObjectAccess::setProperty()` to make use of 

- `templatePathAndFilename`
- `layoutRootPath`
- `partialRootPath`
- `format`

if set directly in `$renderingOptions`.

The results is that those options are not set at all, since those properties are not existing in the view not do setters exist. Instead `setOption()` would need to be used.

In the end a user has to set the (no longer working) `templatePathAndFilename` (to anything non-empty, in fact) to enable custom error view processing _and_ the needed `viewOptions.templatePathAndFilename` to the requested template.

**Comment by kdambekalns** [comment] 2017-11-08 08:10
Another shortcoming: the `viewClassName` is only used if `templatePathAndFilename` is set, even if the view does not need a template. This could be fixed along the way…

**Comment by kitsunet** [comment] 2017-11-08 09:07
Note that IMHO the concept of custom error views is inherently broken because they need the resource wrapper which is not available early on and so you get an exception that the template could not be loaded, masking the original problem. (Could be solved with a fallback probably)

**Comment by kdambekalns** [comment] 2017-11-08 19:10
Well, you can use an absolute path in case you want to handle exceptions that occur "too early". But the concept works well for any "non-500" exceptions, IMHO.

**Comment by mhsdesign** [comment] 2021-11-16 20:51
I had the same problem yesterday - my duplicate issue: #2627

**Comment by mhsdesign** [comment] 2021-11-27 17:09
I thought about just removing the isset() check but the problem is then how to determine if the exception should use renderStatically or a custom view? Seems easy at first: when you have set a viewOption in the rendering group, but thats will not always work, as the custom error view might not need any options like in Neos cms just viewClassName is set:

https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Configuration/Settings.yaml#L480
```
Neos:
  Flow:
    error:
      exceptionHandler:
        renderingGroups:
          notFoundExceptions:
            matchingStatusCodes:
              - 403
              - 404
              - 410
            options:
              viewClassName: \Neos\Neos\View\FusionExceptionView
```
(the above actually only works since the yaml is merged with the flow yaml which defines a templatePathAndFilename for the group notFoundExceptions https://github.com/neos/flow-development-collection/blob/0fd339c365397ed27430b1ce47963ec7761cb934/Neos.Flow/Configuration/Settings.Error.yaml#L25 That leads to that isset() passes and the viewClassName will be used but the templatePathAndFilename is not used but still necessary - the most confusing thing is that templatePathAndFilename is hidden away and the above will not work alone...)

Then i thought about just checking if the renderingGroup has defined either viewClassName or viewOptions but that doesnt work when you want to use a view for every exception and define the settings via defaultRenderingOptions.

So it could be solved by saying a custom view is used, if defaultRenderingOptions.viewOptions is not empty or if the  renderingGroup has defined either viewClassName or viewOptions but this seems weird to me. as one might specify a option in defaultRenderingOptions.viewOptions which should only be merged with the renderingGroup option...

or one could remove that defaultRenderingOptions can be used for all exceptions as view (that could be handled with a renderingGroup with `matchingExceptionClassNames: \Throwable` idk if this works ^^)

**Closed** 2022-03-15 18:11 UTC
Labels: T: PHP, T: Documentation, P: Flow
