### ISSUE TITLE
Compatibility with TYPO3 Fluid 2.6.2 (and 2.6.6)

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#1761] opened 2019-09-09 08:21 UTC
### Description

A test fails:

```
There was 1 failure:

1) Neos\FluidAdaptor\Tests\Functional\View\StandaloneViewTest::xmlNamespacesCanBeIgnored
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'<foo:bar /><bar:foo></bar:foo><foo.bar:baz />foobar'
+'<foo:bar /><bar:foo></bar:foo><foo.bar:baz /><f:format.raw>foobar</f:format.raw>'

…/Packages/Framework/Neos.FluidAdaptor/Tests/Functional/View/StandaloneViewTest.php:282
…/Packages/Framework/Neos.FluidAdaptor/Tests/Functional/View/StandaloneViewTest.php:42
…/Packages/Libraries/phpunit/phpunit/phpunit:61
```

### Steps to Reproduce

1. Install Neos 5.0.x-dev
2. Run functional tests
3. See it fail

#### Actual behavior

My guess: this is caused by Fluid 2.6.2 - in https://travis-ci.org/neos/flow-development-collection/jobs/581986135 it's still 2.6.1 and the tests pass, in https://travis-ci.org/neos/flow-development-collection/jobs/582499795 it's 2.6.2

Looks like this: https://github.com/TYPO3/Fluid/commit/f85a5a7fff02e43f688e31b34d284efb41caf44f (from https://github.com/TYPO3/Fluid/pull/451), claiming:

> Behavior remains unchanged.

… unless you changed the handling that took place in the TemplateProcessor (like we did, AFAICU)

#### Further observations

Doing this in "our" FluidAdaptor RenderingContext:

```
#use Neos\FluidAdaptor\Core\Parser\TemplateProcessor\NamespaceDetectionTemplateProcessor;
use TYPO3Fluid\Fluid\Core\Parser\TemplateProcessor\NamespaceDetectionTemplateProcessor;
```

sees all funtional tests pass, just the one about ignoring namespaces still fails. ~It seems we do not need that processor (anymore).~ That shows we lack a test, see https://github.com/neos/flow-development-collection/issues/1761#issuecomment-529360334 and https://github.com/TYPO3/Fluid/issues/474

Question: do we need that test? Or is that tested in TYPO3 Fluid by now, since that ignoring of namespaces is core functionality?

But: The issue goes deeper, it seems. The test sets a nonce to make sure templates are cached "under our control". That relies on the overridden method `Neos\FluidAdaptor\Tests\Functional\View\Fixtures\View::createIdentifierForFile()` - but that is no longer called… That goes through `TemplatePaths` completely.

Further: I think we don't need our `EscapingFlagProcessor` any longer, the TYPO3 Fluid `EscapingModifierTemplateProcessor` does the same job, only with more options (`SCAN_PATTERN_ESCAPINGMODIFIER = '/{(escaping|escapingEnabled)\s*=*\s*(true|false|on|off)\s*}/i';`).

### Affected Versions

Flow: 6.0.x-dev, possible earlier _with TYPO3 Fluid 2.6.2_

**Comment by kitsunet** [comment] 2019-09-09 08:22
Ok, so something else must be different at your end, because I don't have that error. PHP version?

**Comment by kdambekalns** [comment] 2019-09-09 08:25
- could someone please check if this affects earlier Neos/Flow versions as well?
- if it does, do we roll back https://github.com/neos/flow-development-collection/pull/1757?
- for Flow 6.0 we need to fix this, any volunteers for thoroughly checking our FluidAdaptor for outdated code & assumptions?
- if all else fails, do we adjust our TYPO3 Fluid dependency to 2.6.1 precisely?

**Comment by kitsunet** [comment] 2019-09-09 08:25
The linked Travis failure is 7.3, I am running 7.2 so I strongly assume some PHP 7.3 regex foo?

**Comment by kdambekalns** [comment] 2019-09-09 08:26
This Travis build is 7.2 and fails: https://travis-ci.org/neos/flow-development-collection/jobs/582499791

**Comment by kitsunet** [comment] 2019-09-09 08:29
It's still interesting that I cannot reproduce this on my machine. I have fluid 2.6.2 and 6.0-dev

**Comment by kitsunet** [comment] 2019-09-09 08:31
Ok, so super important thing I didn't know (something to investigate), our functional tests seem prone to cache issues. After flushing the cache I now CAN reproduce this.

**Comment by kitsunet** [comment] 2019-09-09 08:34
@kdambekalns looking at the test I am slightly confused by the test premise though. Shouldn't a ignored namespace be 100% ignored, so the tag should remain in the rendered result, just untouched by fluid, which seems to be the case (now). I don't understand how the original expected results would have made any sense?

**Comment by kdambekalns** [comment] 2019-09-09 08:35
> our functional tests seem prone to cache issues.

Yes, aforementioned "nonce" is no longer used, I'd say.

**Comment by kdambekalns** [comment] 2019-09-09 08:36
No clue about the actual behaviour. That's why I hope @bwaidelich can chime in. But whatever, I think that FluidAdaptor of ours needs some love.

**Comment by kdambekalns** [comment] 2019-09-09 08:39
That PR starts some cleanup. No change to the failing test, but no new failures/errors either.

**Comment by kitsunet** [comment] 2019-09-09 08:39
Note to self and others. For `NamespaceDetectionTemplateProcessor` it seems we miss a test for the CDATA behaviour it implements (so no evaluation but CDATA section is kept in the output) which might explain why running tests without it still works. We should probably add a test that exposes that behaviour and probably rename the processor if possible.

**Comment by kdambekalns** [comment] 2019-09-09 08:43
Related: Are we affected by https://github.com/TYPO3/Fluid/issues/474 if we remove our own processor?

**Comment by kitsunet** [comment] 2019-09-09 08:45
Yes, see above :)

**Comment by bwaidelich** [comment] 2019-09-09 08:49
I'm currently reading through the threads to understand what's going on..
The feature to ignore tags was introduced 5 years ago (eehk!) with https://github.com/neos/flow-development-collection/commit/bd959d034de7e6b5effed475e843be0d1db42301

As for the test:
For the template
```html
{namespace f*}{namespace bar}<foo:bar /><bar:foo></bar:foo><foo.bar:baz /><f:format.raw>foobar</f:format.raw>
```

The output is expected to be
```html
<foo:bar /><bar:foo></bar:foo><foo.bar:baz />foobar
```

because the matching registered namespaces (and `f` is always defined) should take precedence => `f:xyz` is resolved, `foo:bar` is not

**Comment by bwaidelich** [comment] 2019-09-09 08:50
..at least that was the _original_ behavior and the test was meant to document that I guess. I think it would be fine to change the behavior, but it's kind of a breaking change of course

**Comment by kdambekalns** [comment] 2019-09-09 08:53
This is the one part I did not copy here from Slack:

> Looking at https://github.com/TYPO3/Fluid/issues/8#issuecomment-142596139 it seems @bwaidelich might know what this is about…

It mentions FLOW-150, so, yes, I assumed you know more, @bwaidelich :)

**Comment by bwaidelich** [comment] 2019-09-09 08:59
@kdambekalns I'm not sure I get your question. Quick call?

**Comment by kdambekalns** [comment] 2019-09-09 09:01
@bwaidelich No question - just pointed out I had already stumbled over FLOW-150 and your involvement back then. I hope you can help with untangling this, that's all. :)

**Comment by bwaidelich** [comment] 2019-09-09 09:06
Probably I _did_ know more about it.. 4 years ago :)
From looking at the description it seems that the behavior changed recently so that ignored namespaces take precedence of registered ones in Fluid Core. And if that's the case, I don't know if we can do much about it..
I can dig into this one a bit later today!

**Comment by bwaidelich** [comment] 2019-09-09 09:10
I added a comment to https://github.com/TYPO3/Fluid/pull/451

**Comment by NamelessCoder** [comment] 2019-09-09 11:33
Hi Neos team,

First of all - sorry about this regression! Although there were tests for ignored namespace handling, none of them took into consideration that an ignored namespace might be a (partial) match for a registered namespace. I've created https://github.com/TYPO3/Fluid/pull/475 and added a test case that tests for this precise case of ignored NS match.

If you can confirm this solves the issue I will follow up with a bug fix release immediately.

**Comment by kdambekalns** [comment] 2019-09-09 12:15
Thanks, I’ll check that solution later today!

**Comment by albe** [comment] 2019-09-20 11:21
Should be fixed with Fluid 2.6.3 and 2.5.7, see https://github.com/TYPO3/Fluid/pull/475#issuecomment-530788809

so closing. Thanks @NamelessCoder !

**Comment by kdambekalns** [comment] 2019-11-04 13:57
This seems to be back with Fluid 2.6.6, see

- https://travis-ci.org/neos/flow-development-collection/jobs/607095472
- https://travis-ci.org/neos/flow-development-collection/jobs/607095722
- https://travis-ci.org/neos/flow-development-collection/jobs/607095807

**Comment by kdambekalns** [comment] 2019-11-04 14:03
Seems as if https://github.com/TYPO3/Fluid/commit/f8c0fb3753520f78022ddddd52f18466fc4888e1 caused it. What is the background for the revert? I can't seem to find a changelog… 😳

**Comment by albe** [comment] 2019-11-04 15:37
Left a comment on the Fluid issue, maybe Claus can give an answer. Once we know the reasoning, we can act accordingly.

**Comment by NamelessCoder** [comment] 2019-11-05 14:46
Version 2.6.7 has been released - no changes aside from restoring this commit!

**Closed** 2019-11-05 16:08 UTC
Labels: Bug, P: Fluid(Adaptor), T: PHP, T: Testing
