### ISSUE TITLE
Split configuration sources do not work after cache flush

### ISSUE THREAD

**Issue by fnkr** [neos/flow-development-collection#1180] opened 2018-01-15 10:41 UTC
### Description

[Split configuration sources][1] do not work for us since we upgraded from Flow 3 to 4.3.

- If the first Flow call after cache flush is an http request, split configuration sources do not work
- If the first Flow call after cache flush is from the command line (the `./flow` tool), split configuration sources do not work, but do work for subsequent Flow calls

### Steps to Reproduce

**1)** Set up split configuration sources as described [in the docs][1].

This is how our `Packages/Vendor.Site/Classes/Package.php` looks like:

```php
namespace Vendor\Site;

use Neos\Flow\Configuration\ConfigurationManager;
use Neos\Flow\Core\Booting\Sequence;
use Neos\Flow\Core\Bootstrap;
use Neos\Flow\Package\Package as BasePackage;

class Package extends BasePackage
{
    public function boot(Bootstrap $bootstrap)
    {
        $dispatcher = $bootstrap->getSignalSlotDispatcher();

        $dispatcher->connect(ConfigurationManager::class, 'configurationManagerReady',
            function (ConfigurationManager $configurationManager) {
                $configurationManager->registerConfigurationType(
                    ConfigurationManager::CONFIGURATION_TYPE_SETTINGS,
                    ConfigurationManager::CONFIGURATION_PROCESSING_TYPE_SETTINGS,
                    true
                );
            }
        );
    }
}
```

**2)** Add `Packages/Vendor.Site/Configuration/Settings.Foo.yaml`:

```yaml
Vendor:
  Site:
    foo:
      bar: baz
```

**3)** Call Flow via http request or command line and check whether the extra configuration entries are available.

#### Expected behavior

```
$ ./flow flow:cache:flush
Flushed all caches for "Development/Vendor/Local" context.
$ ./flow configuration:show --path Vendor.Site.foo
Configuration "Settings: Vendor.Site.foo":

bar: baz
$ ./flow configuration:show --path Vendor.Site.foo
Configuration "Settings: Vendor.Site.foo":

bar: baz
```

#### Actual behavior

```
$ ./flow flow:cache:flush
Flushed all caches for "Development/Vendor/Local" context.
$ ./flow configuration:show --path Vendor.Site.foo
Configuration "Settings: Vendor.Site.foo" was empty! <========
$ ./flow configuration:show --path Vendor.Site.foo
Configuration "Settings: Vendor.Site.foo":

bar: baz
```

### Affected Versions

Neos: -

Flow: 4.3.2 (upgraded from Flow 3)

[1]: https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/Configuration.html#split-configuration-sources

**Comment by kdambekalns** [comment] 2018-01-15 11:24
Thanks for the detailed issue, awesome!

**Comment by kitsunet** [comment] 2018-01-16 10:04
Just two things:

a) it could be a problem of package order
b) we didn't enable split sources for Settings in Flow, so what you are doing is not covered and tested by us and is fine to break at any point in time.

**Comment by daniellienert** [comment] 2018-01-16 13:29
@kitsunet, thanks for your thoughts: 
a) The Package.php holding the splitSourceConfiguration is in the same Package as the split setting files.
b) The documentation linked above states: 

> Split configuration is only supported for the CONFIGURATION_PROCESSING_TYPE_DEFAULT and CONFIGURATION_PROCESSING_TYPE_SETTINGS processing types.

So I thought this is supported.

**Comment by bwaidelich** [comment] 2018-01-16 15:16
> is fine to break at any point in time

could make a nice claim for the next conference 🤣 
Just kidding. I also suspect an invalid package dependency being the root cause for this. It seems you *override*  the options for an existing configuration type (settings) by calling `ConfigurationManager::registerConfigurationType()` - and if that's called by Flow *at a later point again* it will be reset..

A safer way would be to allow spilt configuration for all types anyways and I think that was the plan sometimes.. Any volunteers?

**Comment by kitsunet** [comment] 2018-01-16 15:23
I can have a look at it after I am done with my PSR stuff. But yeah, I would be OK in general with enabling split sources for Settings, it's just that we never looked at it and I am not sure what impact it has to just enable it via Package.php, so IMHO it's an unplanned change to core functionality.

@daniellienert well, that is meant for your OWN configuration types. Like the ContentRepository introduces the NodeTypes configuration type that has it enabled. But it was not really planned to override core configuration types with it. ;)

**Comment by kdambekalns** [comment] 2018-01-23 08:53
> But it was not really planned to override core configuration types with it. ;)

Well, the main reason we did not enable it for any of the existing types right away was that you could at some point either have split _or_ non-split configuration sources. That was changed at some point (probably when we really wanted to split `NodeTypes.yaml`) and one can now have `Foo.yaml` _and_ `Foo.Bar.yaml` being read together happily.

**Comment by kdambekalns** [comment] 2018-01-23 15:48
I justtalked to @robertlemke and he told me had actually tried enabling split configuration for settings a while back. It worked seemingly, and then everything went up in smoke, as soon as caches were built. Doh.

And he remembers @kitsunet _explaining to him_ why it doesn't work, but not _why it doesn't work_. Unfortunately. ;)

**Comment by daniellienert** [comment] 2018-01-23 17:45
@kdambekalns / @robertlemke / @kitsunet: I hot-fixed the problem for us by patching the ConfigurationManager and setting `'allowSplitSource' => true`  for the configuration type settings. That works flawlessly, even with split and non-split setting files mixed and merged over different sub-contexts, while setting it via package.php had the same problems with caching like you describe.

**Comment by daniellienert** [comment] 2018-01-23 20:19
Just thinking, if that works - why do we have that splitSource switch at all and why is that feature not enabled by default? Are there any performance drawbacks or other issues with it?

**Comment by kdambekalns** [comment] 2018-01-24 11:00
As mentioned earlier, it was not enabled by default when it was invented, since it would have meant to lose `Settings.yaml`, because only that _or_ `Settings.*.yaml` was read.

**Comment by bwaidelich** [comment] 2018-01-24 11:05
IMO it would be a good idea to get rid of the switch in the mid term and read all configuration files in that order: `<ConfigurationType>.yaml`, `<ConfigurationType>.*.yaml`  (possibly also `*.yml`-files, that has been a WTF for many people.. different topic).

I can imagine that we have some parts that check for `Settings.yaml` explicitly (e.g. FileMonitors etc). Those would need to be adjusted of course - so there's a relatively high "chance of breakiness" thus probably a candidate for a major version

**Comment by kdambekalns** [comment] 2018-01-24 11:11
The next major is near! 🎉

**Comment by kitsunet** [comment] 2018-01-24 20:53
There you go.

**Comment by kitsunet** [comment] 2018-01-26 15:48
> IMO it would be a good idea to get rid of the switch in the mid term and read all configuration files in that order

Agreed. Didn't see that earlier. Maybe will give it a go at some point.

**Closed** 2018-01-26 15:47 UTC
Labels: P: Flow
