### ISSUE TITLE
TASK: Harden class name detection

### ISSUE THREAD

**Issue by christophlehmann** [neos/flow-development-collection#2995] opened 2023-03-22 20:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During class name detection 'class name' in the heredoc is interpreted as PHP Code

https://github.com/TYPO3/Fluid/blob/449e5c7105a47f81f3fe5cf28bdaa69039fae0b5/src/Tools/ConsoleRunner.php#L397

This could be optimized/prevented by (?) extending the regexp in https://github.com/neos/flow-development-collection/blob/8.3/Neos.Flow/Classes/ObjectManagement/Proxy/Compiler.php#L251

### Expected Behavior

It is not detected as PHP Code or as a class name

**Comment by mhsdesign** [comment] 2023-03-23 00:02
Hi ;) this seems to be a known issue see: https://github.com/neos/flow-development-collection/issues/1835


But about the usecase: it seems typo3 fluid should not be proxied either way so you might want to exclude it: https://neos-project.slack.com/archives/C04V4C6B0/p1679476831974889

@fcool wrote
The current trouble with typo3fluid/fluid can be solved by removing the includeClasses directive in Settings.yaml like that:
```
Neos:
  Flow:
    object:
      includeClasses:
        'typo3fluid.fluid': []

```

and it looks like the FluidAdaptor can still work without objectmanagement enabled in TYPO3Fluid


Edit: a I see you discussed this already in https://github.com/neos/flow-development-collection/issues/2993#issuecomment-1480223806


So I guess we can just close this as duplicate of #1835

**Comment by kdambekalns** [comment] 2023-03-23 06:40
Duplicate of https://github.com/neos/flow-development-collection/issues/1835

**Closed as completed by kdambekalns** 2023-03-23 06:40 UTC
Labels: Bug
