### ISSUE TITLE
Incompatible with "doctrine/persistence" 2.2

### ISSUE THREAD

**Issue by runner78** [neos/flow-development-collection#2479] opened 2021-05-17 12:11 UTC
### Description

On May 15th "doctrine/persistence 2.2 was released, unfortunately Flow is not compatible with it. 
I added "doctrine/persistence": "2.1.*" to my composer.json as workaround.

### Steps to Reproduce

1. composer update

#### Expected behavior

Should work

#### Error

Exception:
`Cannot convert cache to PSR-6 cache

  Type: BadMethodCallException
  File: Packages/Libraries/doctrine/persistence/lib/Doctrine/Persistence/Mapping/Ab
        stractClassMetadataFactory.php
  Line: 91`

Neos: 7.1

**Comment by albe** [comment] 2021-05-17 13:37
Thanks for the feedback! We'll get this resolved ASAP

See https://github.com/doctrine/persistence/issues/179#issuecomment-842202498

**Comment by alcaeus** [comment] 2021-05-19 07:29
@runner78 I've just released updated versions of doctrine/cache (1.11.1, 2.0.1) and doctrine/persistence (2.2.1) to fix this. Could you please try with those versions and let me know if the issue is fixed? Thanks!

**Comment by albe** [comment] 2021-05-31 15:27
Together with the above and #2482 merged this should now work once released and this issue can IMO be closed :) Please let us know if there are still any problems

**Comment by runner78** [comment] 2021-06-01 10:48
I don't know it is related to flow.

Yesterday i updated an testproject, i have errors about doctrine/orm 2.9, afer i restricted it to 2.8, i have the error with the command "flow doctrine:migrationgenerate":

Doctrine\Common\Cache\Psr6\CacheAdapter::commit(): Return value must be of type bool, null returned

  Type: TypeError
  File: Packages/Libraries/doctrine/cache/lib/Doctrine/Common/Cache/Psr6/CacheAdapter.php
  Line: 210

I had to go again restricted doctrine/persistence to 2.1.

**Comment by mhsdesign** [comment] 2024-01-15 18:46
ill close this as the issue described seems to be fixed by https://github.com/neos/flow-development-collection/pull/2482

`\Doctrine\Common\Cache\Psr6\CacheAdapter::commit` might call -> `\Doctrine\Common\Cache\Cache::save` implemented by -> `\Neos\Flow\Persistence\Doctrine\CacheAdapter::save`

**Closed by mhsdesign** 2024-01-15 18:46 UTC
Labels: T: Database, P: Flow, Bug
