### ISSUE TITLE
BaseUri override in Settings doesn't resprect path

### ISSUE THREAD

**Issue by nixahnung** [neos/flow-development-collection#1215] opened 2018-02-15 10:24 UTC
If i override the baseUri in http:baseuri setting it seems that an additional path is not respected,

Example: baseUri: http://example.com/path/...

Resolved Uri by UriBuilder: http://example.com/...
Path is missing.

Flow: 4.3.3

**Comment by sorenmalling** [comment] 2018-04-09 12:29
Do you install Flow inside a subdirectory or do you want the `/path` as a part of your uri ?

**Comment by bwaidelich** [comment] 2019-11-05 13:29
We had to revert the original fix (#1682) because it introduced a regression. see #1841

**Comment by albe** [comment] 2020-08-06 16:57
This is fixed in 6.0+ as of https://github.com/neos/flow-development-collection/commit/c37b556c2d93b5f3e038eef9fe8663c8fe72837f - now the only question is if we should go the effort to also create a fix for 5.3, as that is the current active bugfix release version. The effort would be much bigger, since the fix can not be simply backported. So I'd be inclined to close this as is.

Any oppinions @bwaidelich @nlx-sascha @nlx-lars @skurfuerst ?

**Comment by skurfuerst** [comment] 2020-08-06 18:27
Agreed @albe 👍

**Comment by nlx-lars** [comment] 2020-08-07 05:49
@albe yes, this can be closed in my opinion 👍

**Comment by nlx-sascha** [comment] 2020-08-07 06:24
@albe fine for me too

**Comment by bwaidelich** [comment] 2020-08-07 06:49
Same here, thanks for taking care. but since @nixahnung opened this ticket: are you fine with this, too - or rather: could you solve this otherwise somehow (duh, this is more than 2 years old already?!)

BTW: I just had a laugh that "nix-lars"¹ and "nix-sascha" comment on an issue from "nixahnung". Are you guys from Gaul? :)


¹ ok, I know that it is "n*L*x", but I read it differently at first

**Comment by albe** [comment] 2020-09-19 15:14
Closing with the above agreement :)

**Closed by albe** 2020-09-19 15:14 UTC
Labels: Bug
