### ISSUE TITLE
Use neos.io as domain for the XSD files

### ISSUE THREAD

**Issue by markusguenther** [neos/flow-development-collection#1186] opened 2018-01-21 23:08 UTC
### Description

The command controller for the creation of the XSD files still uses the typo3.org domain.
This will replace the domain with neos.io

### Steps to Reproduce

1. execute `./flow documentation:generatexsd Neos\\Neos\\ViewHelpers --target-file neos.xsd`
2. take a look at the neos.xsd file header

#### Expected behavior

uses neos.io

#### Actual behavior

uses typo3.org

**Comment by jonnitto** [comment] 2018-05-03 10:08
As there is a PR for this (https://github.com/neos/neos-development-collection/pull/1860 and https://github.com/neos/flow-development-collection/pull/1187) I'll close this issue.

Thank you @markusguenther, we'll discuss and decide on the PR thread.

**Comment by daniellienert** [comment] 2018-05-03 10:55
I reopened the issue. The issue is not closed until the PR is merged - if the PR gets merged the issue will be closed automatically.

**Closed** 2018-11-06 21:50 UTC
