### ISSUE TITLE
Provide Composer 2 compatibility for installer plugin

### ISSUE THREAD

**Issue by robertlemke** [neos/flow-development-collection#2025] opened 2020-06-08 15:24 UTC
Right now, the Flow distribution is not compatible with Composer 2. At least our plugin fails to install due to its dependency constraints:

```
➜  composer create-project neos/neos-base-distribution oidc-demo
Creating a "neos/neos-base-distribution" project at "./oidc-demo"
Installing neos/neos-base-distribution (5.2.1)
  - Installing neos/neos-base-distribution (5.2.1): Extracting archive
Created project in /Users/robert/Sites/oidc-demo
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - neos/redirecthandler-databasestorage[4.0.0, ..., 4.0.2] require neos/flow ~5.0 || ~6.0 -> satisfiable by neos/flow[5.0.0, ..., 5.3.15, 6.0.0, ..., 6.2.0].
    - neos/flow[5.3.9, ..., 5.3.15, 6.0.6, ..., 6.2.0] require neos/composer-plugin ^2.0 -> satisfiable by neos/composer-plugin[2.0.0, 2.0.1].
    - neos/flow[5.0.0, ..., 5.2.14] require neos/composer-plugin ^2.0.0 -> satisfiable by neos/composer-plugin[2.0.0, 2.0.1].
    - neos/flow[5.3.0, ..., 5.3.8, 6.0.0, ..., 6.0.5] require ext-json ^1.2 -> it has the wrong version (7.4.6) installed. Install or enable PHP's json extension.
    - neos/composer-plugin[2.0.0, ..., 2.0.1] require composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires neos/redirecthandler-databasestorage ~4.0 -> satisfiable by neos/redirecthandler-databasestorage[4.0.0, 4.0.1, 4.0.2].

To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/7.4/php.ini
    - /usr/local/etc/php/7.4/conf.d/ext-opcache.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

You are using a snapshot build of Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report an issue to them to ask them to support Composer 2. To work around this you can run Composer with --ignore-platform-req=composer-plugin-api, but this may result in broken plugins and bigger problems down the line.
```

**Comment by kdambekalns** [comment] 2020-06-09 07:53
Duplicate of https://github.com/neos/composer-plugin/issues/13

**Closed by kdambekalns** 2020-06-09 07:53 UTC
Labels: P: Flow, T: PHP
