### ISSUE TITLE
Default orphan removal value for "non aggregate root"-properties is broken

### ISSUE THREAD

**Issue by dwinkelbauer** [neos/flow-development-collection#1127] opened 2017-11-29 10:36 UTC
### Description

After fixing the issue #1079, orphan removal is per default false for properties from classes which are no aggregate roots. 
The problem is that the default value for orphan removal in the ManyToMany, OneToOne and OneToMany annotations is "false". (See [here](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Mapping/OneToMany.php#L55))
Now as [this](https://github.com/neos/flow/blob/17f9801c02e94844895e36e5d567947adef93eaa/Classes/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php#L633) condition does now check, if the value is null and not only if the value is true, orphan removal is always set to false per default. So the following [else if](https://github.com/neos/flow/blob/17f9801c02e94844895e36e5d567947adef93eaa/Classes/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php#L635) for checking if the property is no aggregate root is never evaluated.

This is a major problem, because this minor update can completely change the behavior of an existing application.
### Steps to Reproduce

1. Create a class A with a repository and a class B without a repository
2. Add a property to A from class B e.q. as an OneToMany relation
3. Before #1079 this association had orphanRemovel=true, now it uses orphanRemovel=false per default

#### Expected behavior

orphanRemovel=true 

#### Actual behavior

orphanRemovel=false 

### Affected Versions

Flow: since 4.2.4 and 3.3.20

There is of course the workaround to set orphanRemovel=true manually, but is this the intended approach?

**Comment by albe** [comment] 2017-11-29 10:50
Thanks a lot for bringing this up! It looks indeed like a regression and buggy behaviour.

The question is, what is the expected behaviour? Since orphanRemoval has a default value, there is no way to distinguish the case if this value was implicitly or explicitly set to `false`. I'd expect that if nothing is explicitly set, the fallback rule for aggregate roots is checked and otherwise, the value defaulted to `false`. If however the value is explicity set to `false`, then that should override the aggregate root fallback.

So I only see one solution: remove the default value from the annotation, then add another `else` clause that sets the orphanRemoval to `false`

**Comment by domin1101** [comment] 2017-11-29 17:37
I also thought of removing the default, but as you already said this is not possible.

I think there are only a few other solutions
* Always set orphanRemoval to true for non-aggregate roots, otherwise use the value from the annotation. This would be the same behavior as before #1079, but it would not be possible to set false manually for non-aggregate roots.
* Add another flow annotation, something like "DisableOrphanRemoval" which sets orphanRemoval to false in any case. Only in this way we would get the behavior you described above.

I think the first one would be sufficient or are there any situations where you want to disable orphanRemoval  for non-aggregate roots?

**Comment by dwinkelbauer** [comment] 2017-11-29 17:39
I also thought of removing the default, but as you already said this is not possible.

I think there are only a few other solutions
* Always set orphanRemoval to true for non-aggregate roots, otherwise use the value from the annotation. This would be the same behavior as before #1079, but it would not be possible to set false manually for non-aggregate roots.
* Add another flow annotation, something like "DisableOrphanRemoval" which sets orphanRemoval to false in any case. Only in this way we would get the behavior you described above.

I think the first one would be sufficient or are there any situations where you want to disable orphanRemoval  for non-aggregate roots?

Edit: Sorry wrong account^^

**Comment by kdambekalns** [comment] 2017-12-04 07:44
FYI: I noticed this issue and have it on my "need to comment" list…

**Comment by kitsunet** [comment] 2017-12-04 07:54
Wait, but it should have done the same before, only for ALL falsy values of orphanRemoval (which would include null)

**Comment by albe** [comment] 2017-12-04 11:14
> Add another flow annotation, something like "DisableOrphanRemoval"

I don't think that's a good idea. It is breaky, does not solve the issue with the Doctrine Annotation itself, and adds another framework-specific annotation that has no benefits over the already existing one, other than working around a bug.

> Always set orphanRemoval to true for non-aggregate roots, otherwise use the value from the annotation.

That's probably the better solution, but aren't there use cases where a non-aggregate root should not be orphan removed? (tripple negation ftw) I mean, from a DDD perspective it makes total sense, because only aggregate roots should hold references to their inner entities, so orphanRemoval is natural. But not everyone builds DDD models in Flow, so real world strikes...

> it should have done the same before, only for ALL falsy values of orphanRemoval

Yes, but that was obviously a buggy behaviour. If you specify something explicitely, it should be taken into consideration. Guess we can't fully get out of this though.

I'm actually a bit inclined to move this issue upstream (after doing a quick fix for the breaking regression), because there is no real need for the Doctrine annotations to set default values on the properties and it doesn't for anything other than orphanRemoval and fetch. Also, Doctrine already internally checks for existence of the orphanRemoval mapping setting and defaults it to false there (see e.g. http://www.doctrine-project.org/api/orm/2.5/source-class-Doctrine.ORM.Mapping.ClassMetadataInfo.html#1646), so the change should even be mostly non-breaking.

**Comment by albe** [comment] 2017-12-19 17:17
Seems like we're not going to get a solution from doctrine, but they're having good reasons for that. So I guess we need to solve this differently.

Best approach currently is "Always set orphanRemoval to true for non-aggregate roots, otherwise use the value from the annotation." as far as I see.

**Comment by netfiction** [comment] 2018-01-07 18:32
Is there a solution for this any time soon?
We are stuck on version 3.3.19 as long as this problem isn't solved.

**Comment by kdambekalns** [comment] 2018-01-08 09:52
Finally… sorry for taking so long. Since we want orphan removal for non-aggregate, non-valueobject types, let's just "swap the order of the checks".

**Comment by kdambekalns** [comment] 2018-01-08 09:53
@kitsunet is the milestone you set a "target branch indicator" or a "latest in time" target? I think we should fix this in Flow 3.3 and up…

**Comment by kitsunet** [comment] 2018-01-08 10:09
yes yes, I just want to have it fixed for 4.0 if possible 😆 
Ofc it should go into whatever branch possible as bugfix, if it's non breaking.

**Comment by albe** [comment] 2018-03-16 11:04
Sorry this took so long to actually create a PR for after the decision was made.

**Comment by albe** [comment] 2018-04-05 10:05
Closing this, since this is fixed as far as possible with the above PR. The upcoming releases should contain the fix.

**Closed by albe** 2018-04-05 10:05 UTC
Labels: Bug, P: Flow, T: Database

**Comment by albe** [comment] 2020-10-04 16:14
Seems that with Flow 5.x+ where we require doctrine ORM ^2.6, this now leads to some really bad issue with collections getting deleted on a simple update (@kaystrobach brought this up on slack):
https://github.com/doctrine/orm/issues/6999

Also, as per doctrine assessment (https://github.com/doctrine/orm/issues/6976#issuecomment-360718111 and https://github.com/doctrine/orm/pull/7011/files#r164056022) this is intended behaviour and replacing a `PersistentCollection` (even with a collection with exactly the same elements) on an orphanRemoval relation, leads to such behaviour. The "correct" way is to only `add/remove` from an existing collection instead (IMO doctrine should at least check for equality on the underlying elements array). Funnily enough, see also https://github.com/neos/flow-development-collection/pull/112

From the domain side, as of now, the solution is to build your entity like this:

```php

    /**
     * @var Collection<Child>
     * @ORM\OneToMany(cascade={"persist"}, mappedBy="parent")
     */
    protected $children;

    public function __construct()
    {
        $this->children = new ArrayCollection();
    }

    /**
     * @param Collection $children
     */
    public function setChildren(Collection $children)
    {
        foreach ($this->children as $child) {
            if (!$children->contains($child)) {
                $this->children->removeElement($child);
            }
        }
        foreach ($children as $child) {
            if (!$this->children->contains($child)) {
                $this->children->add($child);
            }
        }
    }
```

cc @kdambekalns @bwaidelich
