### ISSUE TITLE
Response::createFromRaw() chokes on Protocol Upgrade

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#849] opened 2017-02-02 15:26 UTC
When a raw response like this is encountered:

````
HTTP/1.0 200 Connection established

HTTP/1.1 200 OK
Server: openresty
Content-Type: application/json; charset=utf-8
Content-Length: 3202
Vary: Accept-Encoding
Date: Thu, 02 Feb 2017 15:17:42 GMT
Connection: Keep-alive

{"id":"ecfb276920529fc9b9…
````

the resulting response contains the raw "2nd response", which e.g. breaks decoding it as JSON.

This is due to the fact that after an empty line header parsing stops and the remaining lines are considered the response content.

**Comment by kdambekalns** [comment] 2017-02-02 15:26
@robertlemke Interesting, no?

**Comment by albe** [comment] 2017-07-04 13:09
Interesting indeed that this receives a "HTTP/1.0 200" and then another response with "HTTP/1.1 200"... that is *not* a proper protocol upgrade as to my understanding (the first response code should be anything other than 200). Also, this is not a proper response as to HTTP spec, which clearly states that everything after the first empty line is the body. The Response implementation is following spec, so the issue is CURL specific (see also http://php.net/manual/de/function.curl-setopt.php#103232). I guess we need to fix this in `CurlEngine`.

```php
while (substr($response->getContent(), 0, 5) === 'HTTP/') {
   $response = Http\Response::createFromRaw($response->getContent(), $response);
}
```
should do the trick

**Comment by albe** [comment] 2017-10-26 13:28
Closing this as of the merged PR.

**Closed by albe** 2017-10-26 13:28 UTC
Labels: P: Flow, T: PHP
