### ISSUE TITLE
PropertyMapper drops children properties' mapping errors

### ISSUE THREAD

**Issue by domin1101** [neos/flow-development-collection#835] opened 2017-01-24 18:35 UTC
### Description

I have a flow entity with a property from type integer with an IntegerValidator. I have built a standard template + controller, so the user can edit the entity. My problem is that if the user types a not numeric text into the input field for the integer property, the input is ignored without any validation error.

This is caused by the fact that the property mapper ignores child properties whose TypeConverter raises any errors. So the IntegerValidator has no chance to validate the wrong input and no error message is generated. ([See here](https://github.com/neos/flow/blob/master/Classes/Property/TypeConverter/IntegerConverter.php#L66) and [here](https://github.com/neos/flow/blob/master/Classes/Property/PropertyMapper.php#L196))

I'm totally aware that the task of the property mapper is not to validate anything, but nevertheless their should be a possibility to catch such errors and output an error message.

One workaround would be to add a NotEmpty validator to the property, but in this case this is not possible as the property should be nullable.

There already has been an issue on jira, but there hasn't been any updates:
[https://jira.neos.io/projects/FLOW/issues/FLOW-66](https://jira.neos.io/projects/FLOW/issues/FLOW-66)

Also I found a similar (very old) issue for the same problem just for action arguments:
[https://forge.typo3.org/issues/35136](https://forge.typo3.org/issues/35136)

**Comment by albe** [comment] 2017-03-24 13:17
Sorry for the late response and thanks for the explicit description of the issue at hand. We need to discuss and find a solution on how to correctly propagate these errors.

I guess we either collect all errors of subproperties and somehow merge them or directly add them to the messages. Or we just keep the original value if property mapping failed on the sub property, so that the later validator can reject it appropriately.
The big question is what the effects of this change would be, i.e. how breaking it is.

**Comment by albe** [comment] 2017-07-02 18:30
Ok, so after coming back to this and looking closer, I can not really reproduce the wrong behaviour.
If property mapping fails for a subproperty of an object, the according `Error` is added to the validation results and hence submitting an invalid value will result in an error for that property (though not from the Validator, but from the TypeConverter).

This is the case because the property mapper will call `$this->doMapping` recursively and finally end up mapping the single property in question. That in turn will fail and the resulting `Error` will be added to `$this->messages` for the current property path (https://github.com/neos/flow/blob/master/Classes/Property/PropertyMapper.php#L206).

Could you please provide some further information on what the setup was or somehow provide a minimal setup that shows the issue of ignoring the invalid input?

Other than that I just somehow question if e.g. the `IntegerValidator` serves any purpose currently at all (at least on properties instead of direct arguments). If invalid input is provided for an integer property, the TypeConverter will error and hence the IntegerValidator never really kicks in.

**Comment by albe** [comment] 2020-03-08 10:31
Had this pop up again and took another quick look - I still don't see the issue in the code, so closing this now. If anyone digs that up and can provide a reproducible error case, reopen this.

**Closed by albe** 2020-03-08 10:31 UTC
Labels: I: Needs feedback
